commands: # Change single command's permission.
  - "help:bukkit.command.help"
commands-with-plugin: # Change the permissions of all commands in the plugin to which the command belongs
  - "mv:multiverse.use"
messages:
  reload: "&eConfig reload, but it recommended to restart server if you delete some commands."
  help: "&eTry /commandpermissionmanager reload"
bStats: true
